---
# handlers file for jenkins-master
# handlers to enable and restart Jenkins service
  - name: Restart Jenkins service
    ansible.builtin.systemd:
      name: jenkins
      state: restarted
      daemon_reload: true
      enabled: true
...