---
# tasks file to get Jenkins Password

  - shell: "cat {{ jenkins_user.working_directory }}/secrets/initialAdminPassword"
    register: admin_password

  - debug:
      msg: "{{ admin_password.stdout_lines }}"
...